/**
 * Kafka Topic Enum
 */
export enum Topics {
  USER_LOGGER = 'USER_LOGGER',
  USER_EXCEPTIONS = 'USER_EXCEPTIONS',
  USER_ERROR = 'USER_ERROR',
  USER_OPERATION = 'USER_OPERATION',
  FACILITY_LOGGER = 'FACILITY_LOGGER',
  FACILITY_EXCEPTIONS = 'FACILITY_EXCEPTIONS',
  FACILITY_ERROR = 'FACILITY_ERROR',
  FACILITY_OPERATION = 'WINFORM_OPERATION',
  WINFORM_LOGGER = 'WINFORM_LOGGER',
  WINFORM_EXCEPTIONS = 'WINFORM_EXCEPTIONS',
  WINFORM_ERROR = 'WINFORM_ERROR',
  WINFORM_OPERATION = 'WINFORM_OPERATION',
}
